name: distance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  fluttertoast: ^8.2.2
  flutter_screenutil: ^5.9.0
  flutter_blue_plus: ^1.35.5
  permission_handler: ^12.0.1
  vibration: ^3.1.3
  audioplayers: ^6.5.1
  flutter_foreground_task: ^9.1.0
  flutter_local_notifications: ^17.2.3
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
